<?php
return [
    'permissions' => [
        'root' => ['super admin', 'admin', 'owner', 'store', 'customer'],
        'signout' => ['super admin', 'admin', 'owner', 'store', 'customer'],
        //Subscriptions
        'subscription.index' => ['super admin'],
        'subscription.create' => ['super admin'],
        'subscription.store' => ['super admin'],
        'subscription.edit' => ['super admin'],
        'subscription.update' => ['super admin'],
        //Product route
        'product.index' => ['admin', 'owner'],
        'product.create' => ['admin', 'owner'],
        'product.store' => ['admin', 'owner'],
        'product.edit' => ['admin', 'owner'],
        'product.update' => ['admin', 'owner'],
        'product.destroy' => ['admin', 'owner'],
        'product.saleUnit' => ['admin', 'owner'],
        'product.generate.code' => ['admin', 'owner'],
        'product.barcode.generate' => ['admin', 'owner'],
        'barcode.print' => ['admin', 'owner'],
        'product.search' => ['admin', 'owner'],
        'product.item' => ['admin', 'owner'],
        'product.import' => ['admin', 'owner'],
        'product.download.sample' => ['admin', 'owner'],
        'product.print' => ['admin', 'owner'],
        //Stock Count route
        'stockCount.index' => ['admin',   'owner'],
        'stockCount.store' => ['admin',   'owner'],
        //Purchase route
        'purchase.index' => ['admin', 'owner'],
        'purchase.create' => ['admin', 'owner'],
        'purchase.store' => ['admin', 'owner'],
        'purchase.edit' => ['admin', 'owner'],
        'purchase.update' => ['admin', 'owner'],
        'purchase.destroy' => ['admin', 'owner'],
        'product_purchase.search' => ['admin', 'owner'],
        'product_purchase.item' => ['admin', 'owner'],
        'purchase.add-payment' => ['admin', 'owner'],
        'purchase.delete-payment' => ['admin', 'owner'],
        'purchase.batch' => ['admin', 'owner'],
        'purchase.print' => ['admin', 'owner'],
        //category route
        'category.index' => ['admin'],
        'category.store' => ['admin'],
        'category.update' => ['admin'],
        'category.delete' => ['admin'],
        'category.import' => ['admin'],
        'download.sample' => ['admin'],
        'category.print' => ['admin'],
        //Expense Category route
        'expenseCategory.index' => ['admin'],
        'expenseCategory.store' => ['admin'],
        'expenseCategory.update' => ['admin'],
        'expenseCategory.destroy' => ['admin'],
        'expenseCategory.code' => ['admin'],
        //Expense route
        'expense.index' => ['admin'],
        'expense.store' => ['admin'],
        'expense.update' => ['admin'],
        'expense.destroy' => ['admin'],
        //Accounting route
        'account.index' => ['admin'],
        'account.store' => ['admin'],
        'account.update' => ['admin'],
        'account.update.balance' => ['admin'],
        'account.destroy' => ['admin'],
        'account.balancesheet' => ['admin'],
        //Money Transfer route
        'moneyTransfer.index' => ['admin'],
        'moneyTransfer.store' => ['admin'],
        'moneyTransfer.update' => ['admin'],
        'moneyTransfer.destroy' => ['admin'],
        //Money Transfer route
        'transection.index' => ['admin'],
        //Coupon route
        'coupons.index' => ['admin'],
        'coupons.store' => ['admin'],
        'coupons.update' => ['admin'],
        'coupons.destroy' => ['admin'],
        //Gift Cards route
        'gift_cards.index' => ['admin'],
        'gift_cards.store' => ['admin'],
        'gift_cards.update' => ['admin'],
        'gift_cards.destroy' => ['admin'],
        'giftCardCode' => ['admin'],
        'gift_cards.recharge' => ['admin'],
        //Supplier route
        'supplier.index' => ['admin'],
        'supplier.create' => ['admin'],
        'supplier.store' => ['admin'],
        'supplier.edit' => ['admin'],
        'supplier.update' => ['admin'],
        'supplier.destroy' => ['admin'],
        'supplier.import' => ['admin'],
        'download.supplier.sample' => ['admin'],
        //Customer route
        'customer.index' => ['admin'],
        'customer.create' => ['admin'],
        'customer.store' => ['admin'],
        'customer.edit' => ['admin'],
        'customer.update' => ['admin'],
        'customer.destroy' => ['admin'],
        'customer.import' => ['admin'],
        'download.customer.sample' => ['admin'],
        //User route
        'user.index' => ['admin'],
        'user.create' => ['admin'],
        'user.store' => ['admin'],
        'user.edit' => ['admin'],
        'user.update' => ['admin'],
        'user.delete' => ['admin'],
        'profile.index' => ['admin'],
        'profile.update' => ['admin'],
        'user.password' => ['admin'],
        'genPassword' => ['admin'],
        //Sale route
        'sale.index' => ['admin', 'store'],
        'sale.draft' => ['admin', 'store'],
        'sale.draft.delete' => ['admin', 'store'],
        'sale.print' => ['admin', 'store'],
        'sale.pos' => ['admin', 'store'],
        'sale.invoice.generate' => ['admin', 'owner', 'store'],
        //Report Route
        'report.summary' => ['admin'],
        //Sale Return Route
        'sale_returns.index' => ['admin'],
        'sale_returns.search' => ['admin'],
        'sale_returns.details' => ['admin'],
        'sale_returns.product_store' => ['admin'],
        //Role route
        'role.index' => ['admin'],
        'role.store' => ['admin'],
        'role.update' => ['admin'],
        'role.permission' => ['admin'],
        'role.setPermission' => ['admin'],
        //Warehouse route
        'warehouse.index' => ['admin'],
        'warehouse.store' => ['admin'],
        'warehouse.update' => ['admin'],
        'warehouse.delete' => ['admin'],
        //Customer group
        'customer_group.index' => ['admin'],
        'customer_group.store' => ['admin'],
        'customer_group.update' => ['admin'],
        'customer_group.delete' => ['admin'],
        //Brand route
        'brand.index' => ['admin'],
        'brand.store' => ['admin'],
        'brand.update' => ['admin'],
        'brand.delete' => ['admin'],
        //Unit route
        'unit.index' => ['admin'],
        'unit.store' => ['admin'],
        'unit.update' => ['admin'],
        'unit.delete' => ['admin'],
        //Currency route
        'currency.index' => ['admin'],
        'currency.store' => ['admin'],
        'currency.update' => ['admin'],
        'currency.delete' => ['admin'],
        //tax route
        'tax.index' => ['admin'],
        'tax.store' => ['admin'],
        'tax.update' => ['admin'],
        'tax.delete' => ['admin'],
        //Settings route
        'settings.general' => ['admin'],
        'settings.general.store' => ['admin'],
        'settings.mail' => ['admin'],
        'settings.mail.store' => ['admin'],
        // Language
        'language.index' => ['super admin'],
        'language.create' => ['super admin'],
        'language.store' => ['super admin'],
        'language.edit' => ['super admin'],
        'language.update' => ['super admin'],
        'language.delete' => ['super admin'],
    ]
];
